inherit_from: .rubocop_todo.yml

plugins:
  - rubocop-performance
  - rubocop-rails

AllCops:
  Exclude:
    - 'db/**/*'
    - 'config/**/*'
    - 'script/**/*'
    - 'bin/*'
    - 'app/javascript/**/*'
    - '*'
  NewCops: enable
  
Style/StringLiterals:
  EnforcedStyle: double_quotes
Style/FrozenStringLiteralComment:
  Enabled: false
Style/Documentation:
  Enabled: false